Document: liboa
Title: Debian liboa Manual
Author: <insert document author here>
Abstract: This manual describes what liboa is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/liboa/liboa.sgml.gz

Format: postscript
Files: /usr/share/doc/liboa/liboa.ps.gz

Format: text
Files: /usr/share/doc/liboa/liboa.text.gz

Format: HTML
Index: /usr/share/doc/liboa/html/index.html
Files: /usr/share/doc/liboa/html/*.html
